### ISSUE TITLE
Do we need any other code than "latest" in each branch?

### ISSUE THREAD

**Issue by jwikman** [StefanMaron/Dyn365BCSandbox.Code.History#4]
Hi again Stefan

This repo is often a life saver (or at least time-saver 😀).

But when trying to backtrack changes I get totally confused 🤔

It seems as if the hotfixes of all minors are applied to the major branch, which causes changes to be removed and re-applied over and over again.

As a sample for a file in the w1-26 branch:
![Image](https://github.com/user-attachments/assets/de6bb712-587c-468e-b4ec-19d2a5356fd0)

And this is the graph of the w1-25 branch:

![Image](https://github.com/user-attachments/assets/39047303-cd82-4cbe-972c-a6fe1b4d86c3)

Do we really need to apply changes for any other minor than the latest in each branch?

IF there's a need to see all hotfixes for all minors, I believe that we need a branch for each minor. That should probably take less space than the current approach, since we would only commit real changes...

**Comment by StefanMaron** [comment]
> Do we need any other code than "latest" in each branch?

I would say, yes.
Many people compare changes between two specific version, thats why I try to have all the commits in here. 

Changing the branching strategy would mean that I have to rebuild all the branches which will mean we are loosing some history, since it will just take too long to rebuild everything since 23.5 again, like I did here.

In general I would say, that the main repo to work with should be MSDyn365BC.Code.History.
Since there are way less commits and you can better see the "real changes" 

Is there a particular reason you need this Sandbox Repo?

**Comment by jwikman** [comment]
I prefer this repo instead of MSDyn365BC.Code.History since we are all in the cloud.
In the cloud, hotfixes are applied all the time. When troubleshooting strange behaviors, we need to see the latest changes made.

But I'm having a hard time to figure out an efficient way of tracking changes as things are now.
The vNext branch behaves just as I would like it to, for each file we've got a straight commit history (even though I think we should reopen #3 for investigation, there is something strange going on, at least in the vNext branch...)

As an example, yesterday I tried to find in which version of each minor the fix for [this](https://www.yammer.com/dynamicsnavdev/threads/3285796138532864) was applied.

Opening `BaseApp\Source\Base Application\Finance\VAT\Registration\VATRegistrationLogMgt.Codeunit.al` on the w1-26 branch in VSCode gives me the commit history for that file. But I cannot use the blame functionality, since the file is changed back and forth all the time, so I need to scroll through all those "back and forth commits" and check the changes out - to finally find the changes waaay down the list of commits.
Having a clean branch for the major and one for each minor, would make the history way cleaner and easier to follow.

You've absolutely got a point in not changing the current behavior because of the history.

But one approach could be to introduce a new behavior at a new major, for example when BC27 is released, we got one w1-27 that only contains the commits for "latest" on BC27. Then we could have one branch for each minor, like w1-27.1, w1-27.2 and so on.

Or do you have any other suggestion on how to work more efficient here?

**Comment by StefanMaron** [comment]
I started to test a new approach. But its still work in progress.
My idea was to automatically insert hotfixes at the right position and rewrite the order of the commits if needed.
I am not sure if having branches split even more granular would make it better or worse.

But I am working on it :)
https://github.com/StefanMaron/SandboxHistoryBranchingTest

**Comment by jwikman** [comment]
I guess each approach has its own pros and cons... 😅

Wouldn't rewritten commit history behave strange with local clones of the repo? When commit history in a branch is rewritten online, it would seem that I have commits to push to the remote, since my local commits do not exist on the remote. And then there would be needed some tricks to update the local branch - or am I wrong?

One idea could be to start with only doing the per minor branching for one selected localization, as W1 (or base?). In that case we would "only" add 6 more branches per major.

**Comment by StefanMaron** [comment]
Yes, you would need to "force pull".
6 branches is only correct if sandbox artifacts no longer get shipped after the next major is released. (I am not sure if thats the case, or if they continue just like on prem does)

**Comment by jwikman** [comment]
The sandbox artifacts stays at CU5 for each major.
Eg. 24.5.23489.36278 and 25.5.30849.36279 are currently the latest versions on v24 and v25.

**Comment by StefanMaron** [comment]
If everything works, this should now be resolved. vNext gets a complete rebuild, on the current branches, it will only affect future commits

https://github.com/StefanMaron/MSDyn365BC.Sandbox.Code.History?tab=readme-ov-file#branch-history-rewrites

**Comment by jwikman** [comment]
Ok, cool. Then I'll just wait and see how this turns out. 👍

**Comment by StefanMaron** [comment]
Let me know if you see any issues, but I think it works now

<img width="616" height="997" alt="Image" src="https://github.com/user-attachments/assets/517fe08c-f3ff-4ec1-8394-6c53307d267f" />

**Comment by StefanMaron** [comment]
Alright, I noticed one minor inconvenience, but I think thats just something we need to live with.

in de-26.4.37194.40404 we have this change

<img width="2395" height="215" alt="Image" src="https://github.com/user-attachments/assets/84395435-a1e5-4249-8717-efc7c986944f" />

then in de-26.5.38752.40342 it looks like it got removed again

<img width="2234" height="201" alt="Image" src="https://github.com/user-attachments/assets/c61ca4a4-4420-4e4a-9b1a-cb7a79d9c7ab" />


and in de-26.5.38752.40406 it gets added again

<img width="2273" height="195" alt="Image" src="https://github.com/user-attachments/assets/9f3dae30-3030-4f88-9331-ce7839b7cf5a" />

Thats because those changes seem to got back ported into 26.4 so early 26.5 commits dont have it.

**Comment by jwikman** [comment]
My apologies for being grumpy (and old) here... But I believe that this change just moved the issue... 😅

The main issue still exists: Microsoft have different branches for each minor, and here we have only one branch. That's the reason we got the issues that I originally mentioned in this issue, and that is still the reason you got the "inconvenience" you experience after this change.

But thanks to @FBakkensen and the [workflow he created](https://github.com/FBakkensen/bc-w1/blob/main/.github/scripts/update_main_from_w1.sh), we can use your excellent repos as a base for our own repos - crafted to suite our own requirements. I hope that you do not mind! 🙂

**Comment by StefanMaron** [comment]
Oh if you can use what I do to fit your needs thats perfect. 

But I will keep this issue closed now. As I said before, I dont want to blow this repo up even more. The commit where out of order, thats fixed now. resulting in a smaller repo and more convenient commit history.

**Comment by jwikman** [comment]
> Oh if you can use what I do to fit your needs thats perfect.

I think we can accomplish what we wanted with this. :)

> 
> But I will keep this issue closed now. As I said before, I dont want to blow this repo up even more. The commit where out of order, thats fixed now. resulting in a smaller repo and more convenient commit history.

Yes, this one is closed now!

Thanks for your effort on this!
